// src/screens/admin/ClientsScreen/modals/AddClientModal.jsx
import React, { useState } from 'react';
import {
  Modal,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Dimensions,
  TouchableWithoutFeedback,
} from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import DatePicker from 'react-native-date-picker'; // Assuming you use this for date selection
import moment from 'moment'; // For date formatting

const { width, height } = Dimensions.get('window');

const AddClientModal = ({ isVisible, onClose, onSave }) => {
  // Client ID state is removed, as it will be generated by the parent
  const [clientName, setClientName] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [comingDate, setComingDate] = useState(new Date()); // Initialize with current date
  const [openDatePicker, setOpenDatePicker] = useState(false); // State for date picker visibility

  const [customAlertVisible, setCustomAlertVisible] = useState(false);
  const [customAlertMessage, setCustomAlertMessage] = useState('');

  const showCustomAlert = message => {
    setCustomAlertMessage(message);
    setCustomAlertVisible(true);
  };

  const hideCustomAlert = () => {
    setCustomAlertVisible(false);
    setCustomAlertMessage('');
  };

  const resetForm = () => {
    setClientName('');
    setPhoneNumber('');
    setComingDate(new Date());
  };

  // 💾 Handle Save: validate, then pass data up to parent
  const handleSave = () => {
    const trimmedClientName = clientName.trim();
    const trimmedPhoneNumber = phoneNumber.trim();

    if (!trimmedClientName || !trimmedPhoneNumber) {
      showCustomAlert('Please fill in Client Name and Phone Number.');
      return;
    }

    // Clean phone number (remove spaces, dashes, parentheses)
    const cleanPhoneNumber = trimmedPhoneNumber.replace(/[\s\-\(\)]/g, '');

    // Validate phone number length (11-13 digits)
    if (cleanPhoneNumber.length < 11 || cleanPhoneNumber.length > 13) {
      showCustomAlert('Phone number must be 11-13 digits long');
      return;
    }

    // Validate phone number format (must start with 03 or +92)
    if (
      !cleanPhoneNumber.startsWith('03') &&
      !cleanPhoneNumber.startsWith('+92')
    ) {
      showCustomAlert('Phone number must start with 03 or +92');
      return;
    }

    const clientData = {
      name: trimmedClientName,
      phoneNumber: cleanPhoneNumber,
      comingDate: moment(comingDate).format('MMMM DD, YYYY'),
    };
    // Pass data to parent; parent will call API and handle list refresh
    if (onSave) {
      onSave(clientData);
    }
    resetForm();
    onClose();
  };

  const handleClose = () => {
    resetForm();
    onClose();
  };

  return (
    <Modal
      animationType="fade"
      transparent={true}
      visible={isVisible}
      onRequestClose={handleClose}
    >
      <TouchableWithoutFeedback onPress={handleClose}>
        <View style={styles.centeredView}>
          <TouchableWithoutFeedback>
            <View style={styles.modalView}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Add Direct New Client</Text>
                <TouchableOpacity
                  onPress={handleClose}
                  style={styles.crossButton}
                >
                  <Ionicons
                    name="close-circle-outline"
                    size={width * 0.03}
                    color="#A9A9A9"
                  />
                </TouchableOpacity>
              </View>

              {/* Client ID input removed */}
              <TextInput
                style={styles.input}
                placeholder="Client Name"
                placeholderTextColor="#A9A9A9"
                value={clientName}
                onChangeText={setClientName}
              />
              <TextInput
                style={styles.input}
                placeholder="e.g., 03001234567 or +923001234567"
                placeholderTextColor="#A9A9A9"
                keyboardType="phone-pad"
                value={phoneNumber}
                onChangeText={setPhoneNumber}
              />

              {/* Coming Date Picker */}
              <TouchableOpacity
                style={styles.datePickerInput}
                onPress={() => setOpenDatePicker(true)}
              >
                <Text style={styles.datePickerText}>
                  {moment(comingDate).format('MMMM DD, YYYY')}
                </Text>
                <Ionicons
                  name="calendar-outline"
                  size={width * 0.018}
                  color="#A9A9A9"
                />
              </TouchableOpacity>

              <DatePicker
                modal
                mode="date"
                open={openDatePicker}
                date={comingDate}
                onConfirm={date => {
                  setOpenDatePicker(false);
                  setComingDate(date);
                }}
                onCancel={() => setOpenDatePicker(false)}
              />

              <View style={styles.buttons}>
                <TouchableOpacity
                  style={styles.closeButton}
                  onPress={handleClose}
                >
                  <Text style={styles.closeButtonText}>Close</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.saveButton}
                  onPress={handleSave}
                >
                  <Text style={styles.saveButtonText}>Save</Text>
                </TouchableOpacity>
              </View>
            </View>
          </TouchableWithoutFeedback>
        </View>
      </TouchableWithoutFeedback>

      {/* Custom Alert Modal */}
      <Modal
        animationType="fade"
        transparent={true}
        visible={customAlertVisible}
        onRequestClose={hideCustomAlert}
      >
        <View style={styles.customAlertCenteredView}>
          <View style={styles.customAlertModalView}>
            <Text style={styles.customAlertModalText}>
              {customAlertMessage}
            </Text>
            <TouchableOpacity
              style={styles.customAlertCloseButton}
              onPress={hideCustomAlert}
            >
              <Text style={styles.customAlertCloseButtonText}>OK</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </Modal>
  );
};

const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalView: {
    width: width * 0.48,
    backgroundColor: '#1F1F1F',
    borderRadius: 10,
    padding: width * 0.02,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: height * 0.02,
  },
  modalTitle: {
    fontSize: width * 0.025,
    fontWeight: 'bold',
    color: '#fff',
  },
  crossButton: {
    padding: width * 0.004,
  },
  input: {
    width: '100%',
    backgroundColor: '#2A2D32',
    borderRadius: 8,
    padding: width * 0.022,
    marginBottom: height * 0.015,
    color: '#fff',
    fontSize: width * 0.014,
    borderWidth: 1,
    borderColor: '#4A4A4A',
  },
  datePickerInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: '#2A2D32',
    borderRadius: 8,
    padding: width * 0.022,
    marginBottom: height * 0.015,
    borderWidth: 1,
    borderColor: '#4A4A4A',
  },
  datePickerText: {
    color: '#fff',
    fontSize: width * 0.014,
  },
  buttons: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    gap: width * 0.02,
  },
  saveButton: {
    backgroundColor: '#A98C27',
    borderRadius: 8,
    paddingHorizontal: width * 0.08,
    paddingVertical: height * 0.015,
    alignItems: 'center',
    marginTop: height * 0.02,
    marginBottom: height * 0.01,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: width * 0.018,
    fontWeight: 'bold',
  },
  closeButton: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.08,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3C3C3C',
    alignItems: 'center',
    marginTop: height * 0.02,
    marginBottom: height * 0.01,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: width * 0.018,
    fontWeight: 'bold',
  },
  customAlertCenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  customAlertModalView: {
    margin: 20,
    backgroundColor: '#1F1F1F',
    borderRadius: 10,
    padding: 35,
    alignItems: 'center',
    elevation: 5,
  },
  customAlertModalText: {
    marginBottom: 15,
    textAlign: 'center',
    color: '#fff',
    fontSize: width * 0.02,
  },
  customAlertCloseButton: {
    backgroundColor: '#A98C27',
    borderRadius: 5,
    padding: 10,
    elevation: 2,
  },
  customAlertCloseButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default AddClientModal;
